require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoardThreadsController do

  # This should return the minimal set of attributes required to create a valid
  # BoardThread. As you add validations to BoardThread, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      title: 'unko',
      hostname: 'localhost',
      board_key: 'board_001',
      thread_key: 'thread_001',

    }
  end

  describe "GET index" do
    it "assigns all board_threads as @board_threads" do
      board_thread = BoardThread.create! valid_attributes
      get :index
      assigns(:board_threads).should eq([board_thread])
    end
  end

  describe "GET show" do
    it "assigns the requested board_thread as @board_thread" do
      board_thread = BoardThread.create! valid_attributes
      get :show, :id => board_thread.id.to_s
      assigns(:board_thread).should eq(board_thread)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BoardThread" do
        expect {
          post :create, :board_thread => valid_attributes
        }.to change(BoardThread, :count).by(1)
      end

      it "assigns a newly created board_thread as @board_thread" do
        post :create, :board_thread => valid_attributes
        assigns(:board_thread).should be_a(BoardThread)
        assigns(:board_thread).should be_persisted
      end

      it "redirects to the created board_thread" do
        post :create, :board_thread => valid_attributes
        response.should redirect_to(BoardThread.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved board_thread as @board_thread" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoardThread.any_instance.stub(:save).and_return(false)
        post :create, :board_thread => {}
        assigns(:board_thread).should be_a_new(BoardThread)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested board_thread" do
      board_thread = BoardThread.create! valid_attributes
      expect {
        delete :destroy, :id => board_thread.id.to_s
      }.to change(BoardThread, :count).by(-1)
    end

    it "redirects to the board_threads list" do
      board_thread = BoardThread.create! valid_attributes
      delete :destroy, :id => board_thread.id.to_s
      response.should redirect_to(root_url)
    end
  end

end
